### ISSUE TITLE
Allow external user to upload files?

### ISSUE THREAD

**Issue by mahitha-raj** [Submissions/MFTS-issues#1]
**This is in regard to RT #13998** (https://rt.hgsc.bcm.edu/Ticket/Display.html?id=13998)

- We recently agreed that Submissions team would regulate files that get uploaded into the Aspera volume
- Since MFTS uses Aspera, we would then regulate the files that are shared via MFTS

**Case:
An external user 'phenodb' has been uploading a file into their 'phenodb' directory everyday (currently there is one file for everyday since May 21, 2019). User's account was created April 2018.**

Questions:
1. Do we allow uploads on a case-by-case basis?  
2. Is there a size limit for the uploads?
3. Suggestions for tracking users that upload files?

**Comment by walkerh** [comment]
This is a special case. It is not a human uploading files but a bot that uploads a daily snapshot supporting phenodb.

1. Yes.
2. Small (<20MB) files, <500 MB total.
3. Manage this and similar metadata in this directory: `/aspera/share/mfts/tracking` (permissions `drwxrwsr-x`).

**Comment by mahitha-raj** [comment]
Current directory permissions are:
`drwxrwsr-x  2 hale submissions 1470 Jun 20 06:11 phenodb`

In this case, our only option would be to change the group ownership to `mfts`.  Is that okay?

**Comment by walkerh** [comment]
GoAnywhere doesn't care about filesystem permissions. It runs as `root`.

Nevertheless, setting everything under `/aspera/share/mfts` to the `mfts` group would probably be a good idea, but not for the sake of enabling upload. It is good, but not necessary.

**Comment by walkerh** [comment]
I have initiated the group transfer from `submissions` to `mfts` for all of the `mfts` directory.

**Comment by walkerh** [comment]
I thought GoAnywhere might be running as non-root, but that seems to be not the case.

- `ssh -t sug-login4.hgsc.bcm.edu ssh hgsc-sftp1`
- `ps -ef`:

```
...
root      5583     1 34 Jun19 ?        4-19:59:36 /usr/java/latest/bin/java
-Djava.util.logging.config.file=/usr/local/Linoma_Software/GoAnywhere_Services/tomcat/conf/logging.properties
-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
-Xmx8192m
-XX:MaxPermSize=512m
-Djava.awt.headless=true
-XX:-UseVMInterruptibleIO
-Djava.security.egd=file:///dev/urandom
-Djava.endorsed.dirs=/usr/local/Linoma_Software/GoAnywhere_Services/tomcat/endorsed
-classpath
    /usr/local/Linoma_Software/GoAnywhere_Services/tomcat/bin/goanywhere_bootstrap.jar:\
    /usr/local/Linoma_Software/GoAnywhere_Services/tomcat/bin/tomcat-juli.jar
-Dcatalina.base=/usr/local/Linoma_Software/GoAnywhere_Services/tomcat
-Dcatalina.home=/usr/local/Linoma_Software/GoAnywhere_Services/tomcat
-Djava.io.tmpdir=/ftpmount/data
-Duser.dir=/usr/local/Linoma_Software/GoAnywhere_Services
com.linoma.bootstrap.GoAnywhereBootstrap
start
...
```

See #3 for a temporary fix.

**Comment by itsmarcy** [comment]
Just to add/document:
Someone else if having that issue now (https://rt.hgsc.bcm.edu/Ticket/Display.html?id=14010).
In their case it is not the same directory as **phenodb** but in this case the **venner* directory.
So a temp fix would have to be applied there as well.

**Comment by mahitha-raj** [comment]
A test upload to `phenodb` worked.  Here are the permissions and groups for the uploaded file:
`-rw-r--r-- 1 nfsnobody mfts      15 Jul  3 15:09 test.txt`

**Comment by mahitha-raj** [comment]
Also, to add to this, I did not have permissions to remove this file, though I believe @walkerh does have permissions.
Path to test file: `/aspera/share/mfts/private/phenodb/test.txt`

**Comment by walkerh** [comment]
The "t" in `drwxrwxrwt` means that only the owner of the file or the owner of the directory can remove the file. (This is the normal practice for `/tmp` directories.)

I have removed the `test.txt` file. The phenodb user can remove stale files.

**Comment by walkerh** [comment]
@mahitha-raj please write this up into a new file: [`BCM-HGSC/Submissions`](/BCM-HGSC/Submissions)`/docs/mfts/user-upload.md`.

Then close this ticket.

**Comment by walkerh** [comment]
@mahitha-raj do you need any help on this? If not, I will remove the "question" label.

**Comment by mahitha-raj** [comment]
Write up of this issue has been uploaded to `BCM-HGSC/Submissions` [here](https://github.com/BCM-HGSC/submissions/blob/master/docs/mfts/user-upload.md)
