### ISSUE TITLE
Make phenodb directory world writeable

### ISSUE THREAD

**Issue by walkerh** [Submissions/MFTS-issues#3]

**Comment by walkerh** [comment]
`drwxrwxrwt`

@mahitha-raj , please give it a try and then close this ticket if you can upload to phenodb.

**Comment by mahitha-raj** [comment]
A test upload to phenodb worked. Here are the permissions and groups for the uploaded file:
-rw-r--r-- 1 nfsnobody mfts 15 Jul 3 15:09 test.txt 

More information here: #1
