### ISSUE TITLE
Do we need a separate repo for MFTS-issues?

### ISSUE THREAD

**Issue by walkerh** [Submissions/MFTS-issues#4]
Why not just put all theses issues inside the submissions repo?

Keeping this ([MFTS-issues](https://github.com/Submissions/MFTS-issues)) repo:

- Issues private to team
- Either:
  - Increases the loading time for the team-sup workspace
  - Requires use of multiple workspaces

Using [BCM-HGSC/submissions](https://github.com/BCM-HGSC/submissions):

- Issues visible outside team
- Reduces the loading time for the team-sup workspace
- Does not drive the need for multiple workspaces
- Easy to transfer existing issues

**Comment by mahitha-raj** [comment]
Could we rename it to MFTS-cleanup and keep it for now?  
This repo would only act as internal tracking of RT tickets and their related directories that now need to be cleaned up.  It can be temporary and deleted in a couple of months once legacy shares are removed from Aspera.

Other issues related to MFTS can be discussed and tracked under BCM-HGSC/submissions!

**Comment by mahitha-raj** [comment]
Example issue for internal tracking of clean-up: [joy's old mfts shares](https://github.com/Submissions/MFTS-issues/issues/5)

Suggestions or alternatives?

**Comment by walkerh** [comment]
I will move the issues.

**Comment by mahitha-raj** [comment]
Deleted the example issue (it is now part of a larger clean-up issue in BCM-HGSC/submissions).
Using labels is working out well!  No longer require this repo.
